package com.example.kpm.ksoap.src;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.1.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


public interface PWNIServiceEvents
{
    void Starting();
    void Completed(PWNOperationResult result);
}
