package com.example.kpm.ksoap.src;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.1.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public  class PWNLastLoginDetail extends AttributeContainer implements KvmSerializable
{

    
    private transient Object __source;
    
    private String IP;
    
    private Integer account;
    
    private Long date;
    
    public String getIP()
    {
        return this.IP;
    }
    
    public void setIP(String value)
    {
        this.IP = value;     
    }
    
    public Integer getAccount()
    {
        return this.account;
    }
    
    public void setAccount(Integer value)
    {
        this.account = value;     
    }
    
    public Long getDate()
    {
        return this.date;
    }
    
    public void setDate(Long value)
    {
        this.date = value;     
    }

    

    public void loadFromSoap(Object paramObj, PWNExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,PWNExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("IP"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IP = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IP = (String)obj;
                }
                else{
                    this.IP = "";
                }
            }
            return true;
        }
        if (info.name.equals("account"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.account = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.account = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("date"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.date = Long.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Long){
                    this.date = (Long)obj;
                }
            }
            return true;
        }
        return false;
    }    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IP!=null?this.IP:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.account!=null?this.account:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.date!=null?this.date:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "IP";
                info.namespace= "http://schemas.datacontract.org/2004/07/ClientCabinet_MicroService";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "account";
                info.namespace= "http://schemas.datacontract.org/2004/07/ClientCabinet_MicroService";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.LONG_CLASS;
                info.name = "date";
                info.namespace= "http://schemas.datacontract.org/2004/07/ClientCabinet_MicroService";
            }
}

    @Override
    public void setProperty(int arg0, Object arg1) {

    }

    
}
