package com.example.kpm.ksoap.src;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.1.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class PWNOperationResult< T>
{
    private Exception exception;
    private T result;
    private Object tag;
    private String methodName;
    
    public Exception getException()
    {
        return this.exception;    
    }
    
    public void setException(Exception value)
    {
        this.exception=value;
    }
    
    public T getResult()
    {
        return this.result;    
    }
    
    public void setResult(T value)
    {
        this.result=value;
    }
    
    public Object getTag()
    {
        return this.tag;    
    }
    
    public void setTag(Object value)
    {
        this.tag=value;
    }
    
    public String getMethodName()
    {
        return this.methodName;    
    }
    
    public void setMethodName(String value)
    {
        this.methodName=value;
    }
}
